function add_matches(draw)
{
  draw.add_match(  1, "Group A"        , "June 11, 2026",  "1:00 p.m.", -6,            "Estadio Azteca, Mexico City",            "Mexico", "South Africa"  );
  draw.add_match(  2, "Group A"        , "June 11, 2026",  "8:00 p.m.", -6,                 "Estadio Akron, Zapopan",     "Korea Republic", "Czech Republic" );
  draw.add_match( 25, "Group A"        , "June 18, 2026", "12:00 p.m.", -4,         "Mercedes-Benz Stadium, Atlanta",     "Czech Republic", "South Africa"  );
  draw.add_match( 28, "Group A"        , "June 18, 2026",  "7:00 p.m.", -6,                 "Estadio Akron, Zapopan",            "Mexico", "Korea Republic" );
  draw.add_match( 53, "Group A"        , "June 24, 2026",  "7:00 p.m.", -6,            "Estadio Azteca, Mexico City",     "Czech Republic", "Mexico"        );
  draw.add_match( 54, "Group A"        , "June 24, 2026",  "7:00 p.m.", -6,                "Estadio BBVA, Guadalupe",      "South Africa", "Korea Republic" );
  draw.add_match(  3, "Group B"        , "June 12, 2026",  "3:00 p.m.", -4,                     "BMO Field, Toronto",            "Canada", "Bosnia-Herzegovina" );
  draw.add_match(  8, "Group B"        , "June 13, 2026", "12:00 p.m.", -7,            "Levi's Stadium, Santa Clara",             "Qatar", "Switzerland"   );
  draw.add_match( 26, "Group B"        , "June 18, 2026", "12:00 p.m.", -7,                "SoFi Stadium, Inglewood",       "Switzerland", "Bosnia-Herzegovina" );
  draw.add_match( 27, "Group B"        , "June 18, 2026",  "3:00 p.m.", -7,                    "BC Place, Vancouver",            "Canada", "Qatar"         );
  draw.add_match( 51, "Group B"        , "June 24, 2026", "12:00 p.m.", -7,                    "BC Place, Vancouver",       "Switzerland", "Canada"        );
  draw.add_match( 52, "Group B"        , "June 24, 2026", "12:00 p.m.", -7,                   "Lumen Field, Seattle",     "Bosnia-Herzegovina", "Qatar"         );
  draw.add_match(  7, "Group C"        , "June 13, 2026",  "6:00 p.m.", -4,       "MetLife Stadium, East Rutherford",            "Brazil", "Morocco"       );
  draw.add_match(  5, "Group C"        , "June 13, 2026",  "9:00 p.m.", -4,           "Gillette Stadium, Foxborough",             "Haiti", "Scotland"      );
  draw.add_match( 30, "Group C"        , "June 19, 2026",  "6:00 p.m.", -4,           "Gillette Stadium, Foxborough",          "Scotland", "Morocco"       );
  draw.add_match( 29, "Group C"        , "June 19, 2026",  "8:30 p.m.", -4,  "Lincoln Financial Field, Philadelphia",            "Brazil", "Haiti"         );
  draw.add_match( 49, "Group C"        , "June 24, 2026",  "6:00 p.m.", -4,       "Hard Rock Stadium, Miami Gardens",          "Scotland", "Brazil"        );
  draw.add_match( 50, "Group C"        , "June 24, 2026",  "6:00 p.m.", -4,         "Mercedes-Benz Stadium, Atlanta",           "Morocco", "Haiti"         );
  draw.add_match(  4, "Group D"        , "June 12, 2026",  "6:00 p.m.", -7,                "SoFi Stadium, Inglewood",     "United States", "Paraguay"      );
  draw.add_match(  6, "Group D"        , "June 13, 2026",  "9:00 p.m.", -7,                    "BC Place, Vancouver",         "Australia", "Turkey"        );
  draw.add_match( 32, "Group D"        , "June 19, 2026", "12:00 p.m.", -7,                   "Lumen Field, Seattle",     "United States", "Australia"     );
  draw.add_match( 31, "Group D"        , "June 19, 2026",  "8:00 p.m.", -7,            "Levi's Stadium, Santa Clara",            "Turkey", "Paraguay"      );
  draw.add_match( 59, "Group D"        , "June 25, 2026",  "7:00 p.m.", -7,                "SoFi Stadium, Inglewood",            "Turkey", "United States" );
  draw.add_match( 60, "Group D"        , "June 25, 2026",  "7:00 p.m.", -7,            "Levi's Stadium, Santa Clara",          "Paraguay", "Australia"     );
  draw.add_match( 10, "Group E"        , "June 14, 2026", "12:00 p.m.", -5,                   "NRG Stadium, Houston",           "Germany", "Curacao"       );
  draw.add_match(  9, "Group E"        , "June 14, 2026",  "7:00 p.m.", -4,  "Lincoln Financial Field, Philadelphia",       "Ivory Coast", "Ecuador"       );
  draw.add_match( 33, "Group E"        , "June 20, 2026",  "4:00 p.m.", -4,                     "BMO Field, Toronto",           "Germany", "Ivory Coast"   );
  draw.add_match( 34, "Group E"        , "June 20, 2026",  "7:00 p.m.", -5,         "Arrowhead Stadium, Kansas City",           "Ecuador", "Curacao"       );
  draw.add_match( 55, "Group E"        , "June 25, 2026",  "4:00 p.m.", -4,  "Lincoln Financial Field, Philadelphia",           "Curacao", "Ivory Coast"   );
  draw.add_match( 56, "Group E"        , "June 25, 2026",  "4:00 p.m.", -4,       "MetLife Stadium, East Rutherford",           "Ecuador", "Germany"       );
  draw.add_match( 11, "Group F"        , "June 14, 2026",  "3:00 p.m.", -5,            "AT&amp;T Stadium, Arlington",       "Netherlands", "Japan"         );
  draw.add_match( 12, "Group F"        , "June 14, 2026",  "8:00 p.m.", -6,                "Estadio BBVA, Guadalupe",            "Sweden", "Tunisia"       );
  draw.add_match( 35, "Group F"        , "June 20, 2026", "12:00 p.m.", -5,                   "NRG Stadium, Houston",       "Netherlands", "Sweden"        );
  draw.add_match( 36, "Group F"        , "June 20, 2026", "10:00 p.m.", -6,                "Estadio BBVA, Guadalupe",           "Tunisia", "Japan"         );
  draw.add_match( 57, "Group F"        , "June 25, 2026",  "6:00 p.m.", -5,            "AT&amp;T Stadium, Arlington",             "Japan", "Sweden"        );
  draw.add_match( 58, "Group F"        , "June 25, 2026",  "6:00 p.m.", -5,         "Arrowhead Stadium, Kansas City",           "Tunisia", "Netherlands"   );
  draw.add_match( 16, "Group G"        , "June 15, 2026", "12:00 p.m.", -7,                   "Lumen Field, Seattle",           "Belgium", "Egypt"         );
  draw.add_match( 15, "Group G"        , "June 15, 2026",  "6:00 p.m.", -7,                "SoFi Stadium, Inglewood",              "Iran", "New Zealand"   );
  draw.add_match( 39, "Group G"        , "June 21, 2026", "12:00 p.m.", -7,                "SoFi Stadium, Inglewood",           "Belgium", "Iran"          );
  draw.add_match( 40, "Group G"        , "June 21, 2026",  "6:00 p.m.", -7,                    "BC Place, Vancouver",       "New Zealand", "Egypt"         );
  draw.add_match( 63, "Group G"        , "June 26, 2026",  "8:00 p.m.", -7,                   "Lumen Field, Seattle",             "Egypt", "Iran"          );
  draw.add_match( 64, "Group G"        , "June 26, 2026",  "8:00 p.m.", -7,                    "BC Place, Vancouver",       "New Zealand", "Belgium"       );
  draw.add_match( 14, "Group H"        , "June 15, 2026", "12:00 p.m.", -4,         "Mercedes-Benz Stadium, Atlanta",             "Spain", "Cape Verde"    );
  draw.add_match( 13, "Group H"        , "June 15, 2026",  "6:00 p.m.", -4,       "Hard Rock Stadium, Miami Gardens",      "Saudi Arabia", "Uruguay"       );
  draw.add_match( 38, "Group H"        , "June 21, 2026", "12:00 p.m.", -4,         "Mercedes-Benz Stadium, Atlanta",             "Spain", "Saudi Arabia"  );
  draw.add_match( 37, "Group H"        , "June 21, 2026",  "6:00 p.m.", -4,       "Hard Rock Stadium, Miami Gardens",           "Uruguay", "Cape Verde"    );
  draw.add_match( 65, "Group H"        , "June 26, 2026",  "7:00 p.m.", -5,                   "NRG Stadium, Houston",        "Cape Verde", "Saudi Arabia"  );
  draw.add_match( 66, "Group H"        , "June 26, 2026",  "6:00 p.m.", -6,                 "Estadio Akron, Zapopan",           "Uruguay", "Spain"         );
  draw.add_match( 17, "Group I"        , "June 16, 2026",  "3:00 p.m.", -4,       "MetLife Stadium, East Rutherford",            "France", "Senegal"       );
  draw.add_match( 18, "Group I"        , "June 16, 2026",  "6:00 p.m.", -4,           "Gillette Stadium, Foxborough",              "Iraq", "Norway"        );
  draw.add_match( 42, "Group I"        , "June 22, 2026",  "5:00 p.m.", -4,  "Lincoln Financial Field, Philadelphia",            "France", "Iraq"          );
  draw.add_match( 41, "Group I"        , "June 22, 2026",  "8:00 p.m.", -4,       "MetLife Stadium, East Rutherford",            "Norway", "Senegal"       );
  draw.add_match( 61, "Group I"        , "June 26, 2026",  "3:00 p.m.", -4,           "Gillette Stadium, Foxborough",            "Norway", "France"        );
  draw.add_match( 62, "Group I"        , "June 26, 2026",  "3:00 p.m.", -4,                     "BMO Field, Toronto",           "Senegal", "Iraq"          );
  draw.add_match( 19, "Group J"        , "June 16, 2026",  "8:00 p.m.", -5,         "Arrowhead Stadium, Kansas City",         "Argentina", "Algeria"       );
  draw.add_match( 20, "Group J"        , "June 16, 2026",  "9:00 p.m.", -7,            "Levi's Stadium, Santa Clara",           "Austria", "Jordan"        );
  draw.add_match( 43, "Group J"        , "June 22, 2026", "12:00 p.m.", -5,            "AT&amp;T Stadium, Arlington",         "Argentina", "Austria"       );
  draw.add_match( 44, "Group J"        , "June 22, 2026",  "8:00 p.m.", -7,            "Levi's Stadium, Santa Clara",            "Jordan", "Algeria"       );
  draw.add_match( 69, "Group J"        , "June 27, 2026",  "9:00 p.m.", -5,         "Arrowhead Stadium, Kansas City",           "Algeria", "Austria"       );
  draw.add_match( 70, "Group J"        , "June 27, 2026",  "9:00 p.m.", -5,            "AT&amp;T Stadium, Arlington",            "Jordan", "Argentina"     );
  draw.add_match( 23, "Group K"        , "June 17, 2026", "12:00 p.m.", -5,                   "NRG Stadium, Houston",          "Portugal", "Congo DR"      );
  draw.add_match( 24, "Group K"        , "June 17, 2026",  "8:00 p.m.", -6,            "Estadio Azteca, Mexico City",        "Uzbekistan", "Colombia"      );
  draw.add_match( 47, "Group K"        , "June 23, 2026", "12:00 p.m.", -5,                   "NRG Stadium, Houston",          "Portugal", "Uzbekistan"    );
  draw.add_match( 48, "Group K"        , "June 23, 2026",  "8:00 p.m.", -6,                 "Estadio Akron, Zapopan",          "Colombia", "Congo DR"      );
  draw.add_match( 71, "Group K"        , "June 27, 2026",  "7:30 p.m.", -4,       "Hard Rock Stadium, Miami Gardens",          "Colombia", "Portugal"      );
  draw.add_match( 72, "Group K"        , "June 27, 2026",  "7:30 p.m.", -4,         "Mercedes-Benz Stadium, Atlanta",          "Congo DR", "Uzbekistan"    );
  draw.add_match( 22, "Group L"        , "June 17, 2026",  "3:00 p.m.", -5,            "AT&amp;T Stadium, Arlington",           "England", "Croatia"       );
  draw.add_match( 21, "Group L"        , "June 17, 2026",  "7:00 p.m.", -4,                     "BMO Field, Toronto",             "Ghana", "Panama"        );
  draw.add_match( 45, "Group L"        , "June 23, 2026",  "4:00 p.m.", -4,           "Gillette Stadium, Foxborough",           "England", "Ghana"         );
  draw.add_match( 46, "Group L"        , "June 23, 2026",  "7:00 p.m.", -4,                     "BMO Field, Toronto",            "Panama", "Croatia"       );
  draw.add_match( 67, "Group L"        , "June 27, 2026",  "5:00 p.m.", -4,       "MetLife Stadium, East Rutherford",            "Panama", "England"       );
  draw.add_match( 68, "Group L"        , "June 27, 2026",  "5:00 p.m.", -4,  "Lincoln Financial Field, Philadelphia",           "Croatia", "Ghana"         );
  draw.add_match( 73, "Round of 32"    , "June 28, 2026", "12:00 p.m.", -7,                "SoFi Stadium, Inglewood",                "2A", "2B"            );
  draw.add_match( 76, "Round of 32"    , "June 29, 2026", "12:00 p.m.", -5,                   "NRG Stadium, Houston",                "1C", "2F"            );
  draw.add_match( 74, "Round of 32"    , "June 29, 2026",  "4:30 p.m.", -4,           "Gillette Stadium, Foxborough",                "1E", "3 A/B/C/D/F"   );
  draw.add_match( 75, "Round of 32"    , "June 29, 2026",  "7:00 p.m.", -6,                "Estadio BBVA, Guadalupe",                "1F", "2C"            );
  draw.add_match( 78, "Round of 32"    , "June 30, 2026", "12:00 p.m.", -5,            "AT&amp;T Stadium, Arlington",                "2E", "2I"            );
  draw.add_match( 77, "Round of 32"    , "June 30, 2026",  "5:00 p.m.", -4,       "MetLife Stadium, East Rutherford",                "1I", "3 C/D/F/G/H"   );
  draw.add_match( 79, "Round of 32"    , "June 30, 2026",  "7:00 p.m.", -6,            "Estadio Azteca, Mexico City",                "1A", "3 C/E/F/H/I"   );
  draw.add_match( 80, "Round of 32"    ,  "July 1, 2026", "12:00 p.m.", -4,         "Mercedes-Benz Stadium, Atlanta",                "1L", "3 E/H/I/J/K"   );
  draw.add_match( 82, "Round of 32"    ,  "July 1, 2026",  "1:00 p.m.", -7,                   "Lumen Field, Seattle",                "1G", "3 A/E/H/I/J"   );
  draw.add_match( 81, "Round of 32"    ,  "July 1, 2026",  "5:00 p.m.", -7,            "Levi's Stadium, Santa Clara",                "1D", "3 B/E/F/I/J"   );
  draw.add_match( 84, "Round of 32"    ,  "July 2, 2026", "12:00 p.m.", -7,                "SoFi Stadium, Inglewood",                "1H", "2J"            );
  draw.add_match( 83, "Round of 32"    ,  "July 2, 2026",  "7:00 p.m.", -4,                     "BMO Field, Toronto",                "2K", "2L"            );
  draw.add_match( 85, "Round of 32"    ,  "July 2, 2026",  "8:00 p.m.", -7,                    "BC Place, Vancouver",                "1B", "3 E/F/G/I/J"   );
  draw.add_match( 88, "Round of 32"    ,  "July 3, 2026",  "1:00 p.m.", -5,            "AT&amp;T Stadium, Arlington",                "2D", "2G"            );
  draw.add_match( 86, "Round of 32"    ,  "July 3, 2026",  "6:00 p.m.", -4,       "Hard Rock Stadium, Miami Gardens",                "1J", "2H"            );
  draw.add_match( 87, "Round of 32"    ,  "July 3, 2026",  "8:30 p.m.", -5,         "Arrowhead Stadium, Kansas City",                "1K", "3 D/E/I/J/L"   );
  draw.add_match( 90, "Round of 16"    ,  "July 4, 2026", "12:00 p.m.", -5,                   "NRG Stadium, Houston",              "W 73", "W 75"          );
  draw.add_match( 89, "Round of 16"    ,  "July 4, 2026",  "5:00 p.m.", -4,  "Lincoln Financial Field, Philadelphia",              "W 74", "W 77"          );
  draw.add_match( 91, "Round of 16"    ,  "July 5, 2026",  "4:00 p.m.", -4,       "MetLife Stadium, East Rutherford",              "W 76", "W 78"          );
  draw.add_match( 92, "Round of 16"    ,  "July 5, 2026",  "6:00 p.m.", -6,            "Estadio Azteca, Mexico City",              "W 79", "W 80"          );
  draw.add_match( 93, "Round of 16"    ,  "July 6, 2026",  "2:00 p.m.", -5,            "AT&amp;T Stadium, Arlington",              "W 83", "W 84"          );
  draw.add_match( 94, "Round of 16"    ,  "July 6, 2026",  "5:00 p.m.", -7,                   "Lumen Field, Seattle",              "W 81", "W 82"          );
  draw.add_match( 95, "Round of 16"    ,  "July 7, 2026", "12:00 p.m.", -4,         "Mercedes-Benz Stadium, Atlanta",              "W 86", "W 88"          );
  draw.add_match( 96, "Round of 16"    ,  "July 7, 2026",  "1:00 p.m.", -7,                    "BC Place, Vancouver",              "W 85", "W 87"          );
  draw.add_match( 97, "Quarterfinals"  ,  "July 9, 2026",  "4:00 p.m.", -4,           "Gillette Stadium, Foxborough",              "W 89", "W 90"          );
  draw.add_match( 98, "Quarterfinals"  , "July 10, 2026", "12:00 p.m.", -7,                "SoFi Stadium, Inglewood",              "W 93", "W 94"          );
  draw.add_match( 99, "Quarterfinals"  , "July 11, 2026",  "5:00 p.m.", -4,       "Hard Rock Stadium, Miami Gardens",              "W 91", "W 92"          );
  draw.add_match(100, "Quarterfinals"  , "July 11, 2026",  "8:00 p.m.", -5,         "Arrowhead Stadium, Kansas City",              "W 95", "W 96"          );
  draw.add_match(101, "Semifinals"     , "July 14, 2026",  "2:00 p.m.", -5,            "AT&amp;T Stadium, Arlington",              "W 97", "W 98"          );
  draw.add_match(102, "Semifinals"     , "July 15, 2026",  "3:00 p.m.", -4,         "Mercedes-Benz Stadium, Atlanta",              "W 99", "W 100"         );
  draw.add_match(103, "Match for third place", "July 18, 2026",  "5:00 p.m.", -4,       "Hard Rock Stadium, Miami Gardens",             "L 101", "L 102"         );
  draw.add_match(104, "Final"          , "July 19, 2026",  "3:00 p.m.", -4,       "MetLife Stadium, East Rutherford",             "W 101", "W 102"         );
}
